config/routes.rb
Rails.application.routes.draw do
  root to: "products#index"		
  resources :ware_houses
  resources :products
  resources :product_ware_houses

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/product.rb
class Product < ApplicationRecord
	validates_uniqueness_of :sku_code, presence: true
	validates :name, presence: true	
	validates :price, presence: true
	validates :sku_code, length: { minimum: 8 ,maximum: 8}
	has_many :product_ware_houses ,:dependent => :destroy	
end

app/models/product_ware_house.rb
class ProductWareHouse < ApplicationRecord
	validates :item_count, presence: true	
	validates :low_item_threshold, presence: true	
	belongs_to :product
	belongs_to :ware_house	
end

app/models/ware_house.rb
class WareHouse < ApplicationRecord
	has_many :product_ware_houses ,:dependent => :destroy
	validates :name, presence: true	
	validates :pincode, presence: true
	validates :max_capacity, presence: true
	validates :wh_code, length: { minimum: 4 ,maximum: 16}	
	validates_uniqueness_of :wh_code, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/product_ware_houses_controller.rb
class ProductWareHousesController < ApplicationController
  before_action :set_product_ware_house, only: [:show, :edit, :update, :destroy]

  # GET /product_ware_houses
  # GET /product_ware_houses.json
  def index
    @product_ware_houses = ProductWareHouse.all
  end

  # GET /product_ware_houses/1
  # GET /product_ware_houses/1.json
  def show
  end

  # GET /product_ware_houses/new
  def new
    @product_ware_house = ProductWareHouse.new
  end

  # GET /product_ware_houses/1/edit
  def edit
  end

  # POST /product_ware_houses
  # POST /product_ware_houses.json
  def create
    @product_ware_house = ProductWareHouse.new(product_ware_house_params)
    respond_to do |format|
      if @product_ware_house.save
     
        format.html { redirect_to @product_ware_house, notice: 'Ware house was successfully created.' }
        format.json { render :show, status: :created, location: @product_ware_house }
      else
        format.html { render :new }
        format.json { render json: @product_ware_house.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /product_ware_houses/1
  # PATCH/PUT /product_ware_houses/1.json
  def update
    respond_to do |format|
      if @product_ware_house.update(product_ware_house_params)
        format.html { redirect_to @product_ware_house, notice: 'Ware house was successfully updated.' }
        format.json { render :show, status: :ok, location: @product_ware_house }
      else
        format.html { render :edit }
        format.json { render json: @product_ware_house.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /product_ware_houses/1
  # DELETE /product_ware_houses/1.json
  def destroy
    @product_ware_house.destroy
    respond_to do |format|
      format.html { redirect_to product_ware_houses_url, notice: 'Ware house was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product_ware_house
      @product_ware_house = ProductWareHouse.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def product_ware_house_params
      params.require(:product_ware_house).permit(:low_item_threshold, :item_count)
    end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    @products = Product.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end



  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)
    wares = WareHouse.all
    respond_to do |format|
      if @product.save
      wares.each do |u|
          ProductWareHouse.create(product_id: @product.id , ware_house_id: u.id, item_count: 0, low_item_threshold: 10)
      end
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def product_params
      params.require(:product).permit(:name, :sku_code, :price)
    end
end

app/controllers/ware_houses_controller.rb
class WareHousesController < ApplicationController
  before_action :set_ware_house, only: [:show, :edit, :update, :destroy]

  # GET /ware_houses
  # GET /ware_houses.json
  def index
    @ware_houses = WareHouse.all
  end

  # GET /ware_houses/1
  # GET /ware_houses/1.json
  def show
  end

  # GET /ware_houses/new
  def new
    @ware_house = WareHouse.new
  end

  # GET /ware_houses/1/edit
  def edit
  end

  # POST /ware_houses
  # POST /ware_houses.json
  def create
    @ware_house = WareHouse.new(ware_house_params)
    products = Product.all
    respond_to do |format|
      if @ware_house.save
      products.each do |u|
          ProductWareHouse.create(product_id: u.id , ware_house_id: @ware_house.id, item_count: 0, low_item_threshold: 10)
      end      
        format.html { redirect_to @ware_house, notice: 'Ware house was successfully created.' }
        format.json { render :show, status: :created, location: @ware_house }
      else
        format.html { render :new }
        format.json { render json: @ware_house.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ware_houses/1
  # PATCH/PUT /ware_houses/1.json
  def update
    respond_to do |format|
      if @ware_house.update(ware_house_params)
        format.html { redirect_to @ware_house, notice: 'Ware house was successfully updated.' }
        format.json { render :show, status: :ok, location: @ware_house }
      else
        format.html { render :edit }
        format.json { render json: @ware_house.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ware_houses/1
  # DELETE /ware_houses/1.json
  def destroy
    @ware_house.destroy
    respond_to do |format|
      format.html { redirect_to ware_houses_url, notice: 'Ware house was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ware_house
      @ware_house = WareHouse.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def ware_house_params
      params.require(:ware_house).permit(:name, :wh_code, :pincode, :max_capacity)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/ware_houses_helper.rb
module WareHousesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ms</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/product_ware_houses/_form.html.erb
<%= form_with(model: @product_ware_house, local: true) do |form| %>


  <div class="field">
    <%= form.label :low_item_threshold %>
    <%= form.text_field :low_item_threshold %>
  </div>
  <div class="field">
    <%= form.label :item_count %>
    <%= form.text_field :item_count %>
  </div>  
  <div class="actions">
    <%= form.submit class: 'btn btn-success' %>
  </div>
<% end %>

app/views/product_ware_houses/edit.html.erb
<h1>Editing Ware House</h1>

<%= render 'form', product_ware_house: @product_ware_house %>

<a href="/products", class="btn btn-secondary text-center", style="color:white">Home</a>

app/views/product_ware_houses/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Product Ware Houses</h1>



<a href="/products", class="btn btn-secondary text-center", style="color:white">Home</a>

app/views/product_ware_houses/new.html.erb
<h1>New Ware House</h1>

<%= render 'form', ware_house: @ware_house %>

<%= link_to 'Back', ware_houses_path %>

app/views/product_ware_houses/show.html.erb
<p id="notice"><%= notice %></p>

<a href="/products", class="btn btn-secondary text-center", style="color:white">Home</a>

app/views/products/_form.html.erb
<%= form_with(model: product, local: true) do |form| %>
  <% if product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>
  <div class="field">
    <%= form.label :sku_code %>
    <%= form.text_field :sku_code %>
  </div>
  <div class="field">
    <%= form.label :price %>
    <%= form.text_field :price %>
  </div>
  <div class="actions">
    <%= form.submit class: 'btn btn-success' %>
  </div>
<% end %>
<% unless @product.id.nil?%>
<table class="table-bordered table-striped text-center" style="width:90%">
  <thead>
    <tr>
      <th>Warehouse Name</th>
      <th>Item Count</th>
      <th>Low Item Threshold</th>
      <th colspan="2">Action</th>      
    </tr>
  </thead>

  <tbody>
	<% @product.product_ware_houses.each do |pro| %>
	 <tr>
	   <td><%= pro.ware_house.name%></td>
	   <td>
	   	<%= pro.item_count %></td>
	   <td><%= pro.low_item_threshold %></td>
	   <td><%= link_to 'Edit', edit_product_ware_house_path(pro) %></td>
	 </tr>
	<% end %>
  </tbody>
</table>

<% end %>


app/views/products/edit.html.erb
<h1>Editing product</h1>

<%= render 'form', product: @product %>

<%#= link_to 'Show', @product %> 
<%#= link_to 'Back', products_path %>

app/views/products/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Products</h1>
<div class=" row col-md-12">
  <div class="col-md-6">
    <%= link_to '<button type="button"  class="btn btn-success">Add product</button>'.html_safe, new_product_path %>
  </div>
  <div class="col-md-6">
    <a href="/ware_houses", class="btn btn-primary", style="color:white">Ware Houses</a>
  </div>
</div>
<br>
<table class="table-bordered table-striped text-center" style="width:90%">
  <thead>
    <tr>
      <th>Productcode</th>
      <th>Name</th>
    <th colspan="3">Ware Houses Item count</th> 
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= link_to product.sku_code, edit_product_path(product) %></td>
        <td><%= product.name %></td>        
     <% ProductWareHouse.where(:product_id => product.id).each do |pwh| %> 
     <% if pwh.item_count > pwh.low_item_threshold %> 
            <td><%= pwh.ware_house.name + " "+"("+pwh.item_count.to_s + ")" %></td> 
      <% else %>
            <td style="background-color:red"><%= pwh.ware_house.name + " "+"("+pwh.item_count.to_s + ")" %></td> 
      <% end %>                 
     <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<%#= image_tag @product.avatar.url %>





app/views/products/new.html.erb
<h1>New product</h1>

<%= render 'form', product: @product %>

<%#= link_to 'Back', products_path %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>

app/views/ware_houses/_form.html.erb
<%= form_with(model: ware_house, local: true) do |form| %>
  <% if ware_house.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(ware_house.errors.count, "error") %> prohibited this ware_house from being saved:</h2>

      <ul>
        <% ware_house.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= form.label :wh_code %>
    <%= form.text_field :wh_code %>
  </div>
  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>
  <div class="field">
    <%= form.label :pincode %>
    <%= form.text_field :pincode %>
  </div>
  <div class="field">
    <%= form.label :max_capacity %>
    <%= form.text_field :max_capacity %>
  </div>  
  <div class="actions">
    <%= form.submit class: 'btn btn-success' %>
  </div>
<% end %>

app/views/ware_houses/edit.html.erb
<h1>Editing Ware House</h1>

<%= render 'form', ware_house: @ware_house %>

<%= link_to 'Show', @ware_house %> |
<%= link_to 'Back', ware_houses_path %>

app/views/ware_houses/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Ware Houses</h1>


<div>
<%= link_to '<button type="button"  class="btn btn-success">Add Ware House</button>'.html_safe, new_ware_house_path %>
</div>

<br>
<table class="table-bordered table-striped text-center" style="width:90%">
  <thead>
    <tr>
      <th>Ware House code</th>
      <th>Name</th>
      <th>Pincode</th>
      <th>Max Capacity</th>  
    <th colspan="1">Actions</th>                 
    </tr>
  </thead>

  <tbody>
    <% @ware_houses.each do |ware_house| %>
      <tr>
        <td><%= ware_house.wh_code %>
        <td><%= ware_house.name %>
        <td><%= ware_house.pincode %>
        <td><%= ware_house.max_capacity %>
        <td><%= link_to 'Edit', edit_ware_house_path(ware_house) %></td>
        <td><%= link_to 'Destroy', ware_house, method: :delete, data: { confirm: 'Are you sure?' } %></td>        
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<a href="/products", class="btn btn-secondary text-center", style="color:white">Home</a>

app/views/ware_houses/new.html.erb
<h1>New Ware House</h1>

<%= render 'form', ware_house: @ware_house %>

<%= link_to 'Back', ware_houses_path %>

app/views/ware_houses/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_ware_house_path(@ware_house) %> |
<%= link_to 'Back', ware_houses_path %>